spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.28.166.91:3306/ds_lab?useUnicode=true&characterEncoding=utf8&serverTimezone=CST
    username: remote
    password: 123456

server:
  port: 14514

