spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.28.166.24:3306/ds_lab?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: ds
    password: ds1154459434

# 本地的数据库, 开发时使用
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dslab?useUnicode=true&characterEncoding=utf8&serverTimezone=CST
#    username: root
#    password: 101325

server:
  port: 16663
#logging:
#  level:
#    com.dslab.event.mapper: debug

